### ISSUE TITLE
Can we drop the MailChimp requirement

### ISSUE THREAD

**Issue by jamstooks** [AASHE/django-constant-contact#1]
Mailchimp's api supports CSS-inlining, but there has to be an alternative to making a call to another email marketing company. It just seems weird to me.

[premailer](https://github.com/peterbe/premailer) didn't work because it doesn't support external style sheets?

[inlinestyler](https://github.com/dlanger/inlinestyler) seems to support them...?

**Comment by jamstooks** [comment]
So this doesn't feel like a huge priority to me anymore. It seemed really weird at first, but if it works it works. At the very least we should document it in the readme...

**Comment by rerb** [comment]
Dropped back on 2016-03-18.
