### ISSUE TITLE
Tests not passing on python 2.6

### ISSUE THREAD

**Issue by jamstooks** [AASHE/django-constant-contact#3]
Any chance we could update our tests so that they pass on python 2.6?

**Comment by jamstooks** [comment]
Quick test. Is this showing up in HipChat?

**Comment by jamstooks** [comment]
Trying hipchat again...

**Comment by rerb** [comment]
Fixed.

https://github.com/AASHE/django-constant-contact/commit/72387c4e44086acb549eeaa21b7e7f834865ee4c
